name: CI for Microservices

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-auth:
    name: Build Auth Service
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: UserDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/UserDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      
      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Postgres not ready yet, sleeping 2 seconds..."
            sleep 2
          done
      
      - name: Create UserDB database if not exists
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'UserDB'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE \"UserDB\";"
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - run: mvn clean install test
        working-directory: ./auth-service/auth-service

  build-course:
    name: Build Course Service
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: CourseDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/CourseDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v3

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Postgres not ready yet, sleeping 2 seconds..."
            sleep 2
          done

      - name: Create CourseDB database if not exists
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'CourseDB'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE \"CourseDB\";"
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean install test
        working-directory: ./course-service/course-service

  build-gateway:
    name: Build API Gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean install test
        working-directory: ./api-gateway/api-gateway

  build-user:
    name: Build User Service
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ProfileDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ProfileDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v3

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Postgres not ready yet, sleeping 2 seconds..."
            sleep 2
          done

      - name: Create ProfileDB database if not exists
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'ProfileDB'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE \"ProfileDB\";"
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean install test
        working-directory: ./User-service/User-service

  build-enrollment:
    name: Build Enrollment Service
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: EnrollmentDB
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EnrollmentDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v3

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Postgres not ready yet, sleeping 2 seconds..."
            sleep 2
          done

      - name: Create EnrollmentDB database if not exists
        run: |
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'EnrollmentDB'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE \"EnrollmentDB\";"
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean install test
        working-directory: ./enrollment-service/enrollment-service

  build-eureka:
    name: Build Eureka Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: mvn clean install test
        working-directory: ./eureka-server/eureka-server
